[package]
name = "fast-command-not-found"
version = "0.1.0"
authors = ["Alex Macleod <alex@macleod.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = "1.1.7"
anyhow = "1"
bincode = "1"
flate2 = "1"
fst = { version = "0.4", features = ["levenshtein"] }
getopts = "0.2"
memmap = "0.7"
once_cell = "1"
pacmanconf = "0.2.0"
regex = { version = "1", default-features = false, features = ["std", "perf"] }
serde = { version = "1", features = ["derive"] }
tar = "0.4"
