[package]
name = "fast-command-not-found"
version = "0.1.0"
authors = ["Alex Macleod <alex@macleod.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
once_cell = "1.3.1"
regex = { version = "1", default-features = false, features = ["std", "perf"] }
tar = "0.4"
tempfile = "3"
fst = "0.4.0"
